language: c

env:
 - RACKET_VERSION=6.0
 - RACKET_VERSION=6.0.1
 - RACKET_VERSION=HEAD

before_install:
    ## Racket
    - git clone https://github.com/greghendershott/travis-racket.git
    - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!

    ## Emacs
    - sudo add-apt-repository -y ppa:cassou/emacs
    - sudo apt-get update -qq
    - sudo apt-get -f install
    - sudo apt-get install -qq emacs24 emacs24-el

script:
    ## Run any tests in Racket files
    - /usr/racket/bin/raco test -x .

    ## Test Emacs byte-compile
    - make compile

    ## Emacs tests.
    # TO-DO

