language: generic

env:
  # Emacs 24.3
  - EMACS=emacs24 RACKET_VERSION=5.3.5
  - EMACS=emacs24 RACKET_VERSION=5.3.6
  - EMACS=emacs24 RACKET_VERSION=6.0
  - EMACS=emacs24 RACKET_VERSION=6.0.1
  - EMACS=emacs24 RACKET_VERSION=6.1
  - EMACS=emacs24 RACKET_VERSION=6.1.1
  - EMACS=emacs24 RACKET_VERSION=6.2
  - EMACS=emacs24 RACKET_VERSION=HEAD
  - EMACS=emacs24 RACKET_VERSION=SCOPE_SNAPSHOT
  # Emacs snapshot
  - EMACS=emacs-snapshot RACKET_VERSION=5.3.5
  - EMACS=emacs-snapshot RACKET_VERSION=5.3.6
  - EMACS=emacs-snapshot RACKET_VERSION=6.0
  - EMACS=emacs-snapshot RACKET_VERSION=6.0.1
  - EMACS=emacs-snapshot RACKET_VERSION=6.1
  - EMACS=emacs-snapshot RACKET_VERSION=6.1.1
  - EMACS=emacs-snapshot RACKET_VERSION=6.2
  - EMACS=emacs-snapshot RACKET_VERSION=HEAD
  - EMACS=emacs-snapshot RACKET_VERSION=SCOPE_SNAPSHOT

matrix:
  allow_failures:
    - env: EMACS=emacs24 RACKET_VERSION=HEAD
    - env: EMACS=emacs24 RACKET_VERSION=SCOPE_SNAPSHOT
    - env: EMACS=emacs-snapshot RACKET_VERSION=HEAD
    - env: EMACS=emacs-snapshot RACKET_VERSION=SCOPE_SNAPSHOT
  fast_finish: true

before_install:
  ## Racket
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH=/usr/racket/bin:$PATH

  ## Emacs
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24 &&
        sudo apt-get -qq install emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot &&
        sudo apt-get -qq install emacs-snapshot-el;
    fi

script:
  - make deps EMACSBIN=$EMACS
  - make compile EMACSBIN=$EMACS
  - make test EMACSBIN=$EMACS
